---
title: '20200318'
author: "蕭璟淳"
date: "2020/3/18"
output: html_document
```
---

```{r}
# 狀況二: 倍數堆疊一定會超過，只好截斷
c(2,3)/c(-2,-13,10)
c(2,3,2)/c(-2,-13,10)
```

```{r}
jsonlite::fromJSON("https://www.dropbox.com/s/3uijub7xheib405/list_victimAges_female.json?dl=1", simplifyDataFrame = F) -> list_victimAges_female
str(list_victimAges_female)

```
1.請將list_victimAges_female各元素的class做合理設定。
```{r}
list_victimAges_female$數目<- as.integer(list_victimAges_female$數目)
list_victimAges_female$年齡層<- as.factor(list_victimAges_female$年齡層)
```
2.將levels順序改成: 不詳，總計，0_5歲，12_17歲，…，70歲以上。
```{r}
levels(list_victimAges_female$年齡層) -> levels_ages
print(levels_ages)
```
```{r}
list_victimAges_female$數目 <- as.integer(list_victimAges_female$數目)
pick_na <- is.na(list_victimAges_female$數目)
total_na <- sum(pick_na)
total_na
```

```{r}
source("https://www.dropbox.com/s/qsrw069n94k61lj/transcript100to103_list.R?dl=1")
str(transcript100to103)
```
```{r}
# 各學屆2年級人數
table(transcript100to103$學屆)
# 各學屆2年級成績大於85年數
table(transcript100to103$學屆[pick_above85])
# 只要成績大於85的
pick_above85 <-
  transcript100to103$`成績` > 85
```
創造 可選出來自法商學院的「要/不要」向量，pick_lawBusiness。
```{r}
set_LawBusiness <- c("法學院","商學院")
pick_lawBusiness <-transcript100to103$學院 %in% set_LawBusiness
transcript100to103$成績[pick_lawBusiness]
```
```{r}
factor1 <- factor(
  c("小明","小英")
)
levels(factor1)

is.ordered(factor1)

factor1 < "小英"
```
```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
```


```{r}
)
```
誰1998以後（含）出生或不住大台北
```{r}
install.packages("stringr")
install.packages("glue")
library(stringr)
library(glue)
```
```{r}
addresses <- c(
  '臺中市后里區公館里尾社路385號',
  '新竹市東區科學園路125號1樓',
  '新竹市北區竹光路99號',
  '金門縣金城鎮賢庵里山前33號',
  '臺中市南屯區工業區二十四路23號1樓')
myRegexSlotMachine <- "[0-9]+號"
print(myRegexSlotMachine)
str_view_all(addresses,myRegexSlotMachine)
str_extract(addresses,myRegexSlotMachine)

str_view_all(addresses,"[0-9]+") # 樓號也會選到
```

